name: Native ppc64le Linux Test

on:
  pull_request:
    branches:
      - main
      - maintenance/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  native_ppc64le:
    
    runs-on: ubuntu-24.04-ppc64le
    strategy:
      fail-fast: false
      matrix:
        MESON_OPTIONS:
          - "-Dallow-noblas=true"
          - "-Dallow-noblas=true -Dcpu-baseline=vsx3"
        TEST_FILTER:
          - "test_kind or test_multiarray or test_simd or test_umath or test_ufunc"

    env:
      TERM: xterm-256color

    name: "Native PPC64LE ${{ matrix.MESON_OPTIONS }}"
    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-tags: true
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev cmake ninja-build gfortran \
                            build-essential libopenblas-dev liblapack-dev pkg-config
        pip install --upgrade pip
        pip install -r requirements/build_requirements.txt
        pip install pytest pytest-xdist hypothesis typing_extensions pytest-timeout

    - name: Install spin
      run: |
        python3 -m pip install -U pip setuptools wheel
        python3 -m pip install spin
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Configure Git safe directory
      env:
        HOME: /tmp
      run: |
        git config --global --add safe.directory "$PWD"

    - name: Meson Build
      run: |
        spin build --clean -- ${MESON_OPTIONS}

    - name: Meson Log
      if: always()
      run: cat build/meson-logs/meson-log.txt

    - name: Run Tests
      run: |
        spin test -- --timeout=600 --durations=10
