name: Test PPC64LE Native

on:
  pull_request:
    branches:
      - main
      - maintenance/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  native_ppc64le:
    name: Native PPC64LE
    runs-on: ubuntu-24.04-ppc64le  # make sure the runner is labeled `ppc64le`
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-tags: true
        persist-credentials: false

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-dev cmake ninja-build gfortran \
                            build-essential libopenblas-dev liblapack-dev pkg-config

    - name: Install Python packages
      run: |
        python3 -m pip install -U pip setuptools wheel
        python3 -m pip install spin
        python3 -m pip install -r requirements/ci_requirements.txt
        python3 -m pip install -r requirements/build_requirements.txt -r requirements/test_requirements.txt

    - name: Configure Git safe directory
      env:
        HOME: /tmp
      run: |
        git config --global --add safe.directory "$PWD"

    - name: Build with Meson
      run: |
        spin build --clean --with-scipy-openblas=64

    - name: Run tests
      run: |
        spin test -j auto -- --timeout=600 --durations=10

    - name: Meson Log
      if: always()
      run: cat build/meson-logs/meson-log.txt
